#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VuThanhDuong_DA.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="shs_database")]
	public partial class SHSDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertadmin_account(admin_account instance);
    partial void Updateadmin_account(admin_account instance);
    partial void Deleteadmin_account(admin_account instance);
    partial void Insertuser_order_product(user_order_product instance);
    partial void Updateuser_order_product(user_order_product instance);
    partial void Deleteuser_order_product(user_order_product instance);
    partial void Insertdiscount_event(discount_event instance);
    partial void Updatediscount_event(discount_event instance);
    partial void Deletediscount_event(discount_event instance);
    partial void Insertproduct(product instance);
    partial void Updateproduct(product instance);
    partial void Deleteproduct(product instance);
    partial void Insertproduct_category(product_category instance);
    partial void Updateproduct_category(product_category instance);
    partial void Deleteproduct_category(product_category instance);
    partial void Insertproduct_image(product_image instance);
    partial void Updateproduct_image(product_image instance);
    partial void Deleteproduct_image(product_image instance);
    partial void Insertuser_account(user_account instance);
    partial void Updateuser_account(user_account instance);
    partial void Deleteuser_account(user_account instance);
    partial void Insertuser_order(user_order instance);
    partial void Updateuser_order(user_order instance);
    partial void Deleteuser_order(user_order instance);
    #endregion
		
		public SHSDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["shs_databaseConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SHSDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SHSDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SHSDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SHSDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<admin_account> admin_accounts
		{
			get
			{
				return this.GetTable<admin_account>();
			}
		}
		
		public System.Data.Linq.Table<user_order_product> user_order_products
		{
			get
			{
				return this.GetTable<user_order_product>();
			}
		}
		
		public System.Data.Linq.Table<discount_event> discount_events
		{
			get
			{
				return this.GetTable<discount_event>();
			}
		}
		
		public System.Data.Linq.Table<product> products
		{
			get
			{
				return this.GetTable<product>();
			}
		}
		
		public System.Data.Linq.Table<product_category> product_categories
		{
			get
			{
				return this.GetTable<product_category>();
			}
		}
		
		public System.Data.Linq.Table<product_image> product_images
		{
			get
			{
				return this.GetTable<product_image>();
			}
		}
		
		public System.Data.Linq.Table<user_account> user_accounts
		{
			get
			{
				return this.GetTable<user_account>();
			}
		}
		
		public System.Data.Linq.Table<user_order> user_orders
		{
			get
			{
				return this.GetTable<user_order>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin_account")]
	public partial class admin_account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _admin_account_id;
		
		private string _admin_username;
		
		private string _admin_password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onadmin_account_idChanging(int value);
    partial void Onadmin_account_idChanged();
    partial void Onadmin_usernameChanging(string value);
    partial void Onadmin_usernameChanged();
    partial void Onadmin_passwordChanging(string value);
    partial void Onadmin_passwordChanged();
    #endregion
		
		public admin_account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_account_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int admin_account_id
		{
			get
			{
				return this._admin_account_id;
			}
			set
			{
				if ((this._admin_account_id != value))
				{
					this.Onadmin_account_idChanging(value);
					this.SendPropertyChanging();
					this._admin_account_id = value;
					this.SendPropertyChanged("admin_account_id");
					this.Onadmin_account_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_username", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string admin_username
		{
			get
			{
				return this._admin_username;
			}
			set
			{
				if ((this._admin_username != value))
				{
					this.Onadmin_usernameChanging(value);
					this.SendPropertyChanging();
					this._admin_username = value;
					this.SendPropertyChanged("admin_username");
					this.Onadmin_usernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_password", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string admin_password
		{
			get
			{
				return this._admin_password;
			}
			set
			{
				if ((this._admin_password != value))
				{
					this.Onadmin_passwordChanging(value);
					this.SendPropertyChanging();
					this._admin_password = value;
					this.SendPropertyChanged("admin_password");
					this.Onadmin_passwordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.user_order_product")]
	public partial class user_order_product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_order_id;
		
		private int _product_id;
		
		private EntityRef<product> _product;
		
		private EntityRef<user_order> _user_order;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_order_idChanging(int value);
    partial void Onuser_order_idChanged();
    partial void Onproduct_idChanging(int value);
    partial void Onproduct_idChanged();
    #endregion
		
		public user_order_product()
		{
			this._product = default(EntityRef<product>);
			this._user_order = default(EntityRef<user_order>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_order_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int user_order_id
		{
			get
			{
				return this._user_order_id;
			}
			set
			{
				if ((this._user_order_id != value))
				{
					if (this._user_order.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_order_idChanging(value);
					this.SendPropertyChanging();
					this._user_order_id = value;
					this.SendPropertyChanged("user_order_id");
					this.Onuser_order_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					if (this._product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onproduct_idChanging(value);
					this.SendPropertyChanging();
					this._product_id = value;
					this.SendPropertyChanged("product_id");
					this.Onproduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_user_order_product", Storage="_product", ThisKey="product_id", OtherKey="product_id", IsForeignKey=true)]
		public product product
		{
			get
			{
				return this._product.Entity;
			}
			set
			{
				product previousValue = this._product.Entity;
				if (((previousValue != value) 
							|| (this._product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._product.Entity = null;
						previousValue.user_order_products.Remove(this);
					}
					this._product.Entity = value;
					if ((value != null))
					{
						value.user_order_products.Add(this);
						this._product_id = value.product_id;
					}
					else
					{
						this._product_id = default(int);
					}
					this.SendPropertyChanged("product");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_order_user_order_product", Storage="_user_order", ThisKey="user_order_id", OtherKey="user_order_id", IsForeignKey=true)]
		public user_order user_order
		{
			get
			{
				return this._user_order.Entity;
			}
			set
			{
				user_order previousValue = this._user_order.Entity;
				if (((previousValue != value) 
							|| (this._user_order.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._user_order.Entity = null;
						previousValue.user_order_products.Remove(this);
					}
					this._user_order.Entity = value;
					if ((value != null))
					{
						value.user_order_products.Add(this);
						this._user_order_id = value.user_order_id;
					}
					else
					{
						this._user_order_id = default(int);
					}
					this.SendPropertyChanged("user_order");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.discount_event")]
	public partial class discount_event : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _discount_event_id;
		
		private string _discount_event_name;
		
		private System.Nullable<System.DateTime> _discount_event_begin;
		
		private System.Nullable<System.DateTime> _discount_event_end;
		
		private System.Nullable<int> _product_category_id;
		
		private EntityRef<product_category> _product_category;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondiscount_event_idChanging(int value);
    partial void Ondiscount_event_idChanged();
    partial void Ondiscount_event_nameChanging(string value);
    partial void Ondiscount_event_nameChanged();
    partial void Ondiscount_event_beginChanging(System.Nullable<System.DateTime> value);
    partial void Ondiscount_event_beginChanged();
    partial void Ondiscount_event_endChanging(System.Nullable<System.DateTime> value);
    partial void Ondiscount_event_endChanged();
    partial void Onproduct_category_idChanging(System.Nullable<int> value);
    partial void Onproduct_category_idChanged();
    #endregion
		
		public discount_event()
		{
			this._product_category = default(EntityRef<product_category>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount_event_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int discount_event_id
		{
			get
			{
				return this._discount_event_id;
			}
			set
			{
				if ((this._discount_event_id != value))
				{
					this.Ondiscount_event_idChanging(value);
					this.SendPropertyChanging();
					this._discount_event_id = value;
					this.SendPropertyChanged("discount_event_id");
					this.Ondiscount_event_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount_event_name", DbType="NVarChar(255)")]
		public string discount_event_name
		{
			get
			{
				return this._discount_event_name;
			}
			set
			{
				if ((this._discount_event_name != value))
				{
					this.Ondiscount_event_nameChanging(value);
					this.SendPropertyChanging();
					this._discount_event_name = value;
					this.SendPropertyChanged("discount_event_name");
					this.Ondiscount_event_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount_event_begin", DbType="DateTime")]
		public System.Nullable<System.DateTime> discount_event_begin
		{
			get
			{
				return this._discount_event_begin;
			}
			set
			{
				if ((this._discount_event_begin != value))
				{
					this.Ondiscount_event_beginChanging(value);
					this.SendPropertyChanging();
					this._discount_event_begin = value;
					this.SendPropertyChanged("discount_event_begin");
					this.Ondiscount_event_beginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount_event_end", DbType="DateTime")]
		public System.Nullable<System.DateTime> discount_event_end
		{
			get
			{
				return this._discount_event_end;
			}
			set
			{
				if ((this._discount_event_end != value))
				{
					this.Ondiscount_event_endChanging(value);
					this.SendPropertyChanging();
					this._discount_event_end = value;
					this.SendPropertyChanged("discount_event_end");
					this.Ondiscount_event_endChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_category_id", DbType="Int")]
		public System.Nullable<int> product_category_id
		{
			get
			{
				return this._product_category_id;
			}
			set
			{
				if ((this._product_category_id != value))
				{
					if (this._product_category.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onproduct_category_idChanging(value);
					this.SendPropertyChanging();
					this._product_category_id = value;
					this.SendPropertyChanged("product_category_id");
					this.Onproduct_category_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_category_discount_event", Storage="_product_category", ThisKey="product_category_id", OtherKey="product_category_id", IsForeignKey=true)]
		public product_category product_category
		{
			get
			{
				return this._product_category.Entity;
			}
			set
			{
				product_category previousValue = this._product_category.Entity;
				if (((previousValue != value) 
							|| (this._product_category.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._product_category.Entity = null;
						previousValue.discount_events.Remove(this);
					}
					this._product_category.Entity = value;
					if ((value != null))
					{
						value.discount_events.Add(this);
						this._product_category_id = value.product_category_id;
					}
					else
					{
						this._product_category_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("product_category");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.product")]
	public partial class product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _product_id;
		
		private System.Nullable<int> _product_category_id;
		
		private string _product_name;
		
		private string _product_description;
		
		private string _product_thumbnail_image;
		
		private System.Nullable<decimal> _product_price;
		
		private System.Nullable<decimal> _product_discount;
		
		private System.Nullable<int> _product_review_positive;
		
		private System.Nullable<int> _product_review_negative;
		
		private System.Nullable<int> _product_bought_count;
		
		private System.Nullable<int> _product_inventory;
		
		private EntitySet<user_order_product> _user_order_products;
		
		private EntitySet<product_image> _product_images;
		
		private EntityRef<product_category> _product_category;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproduct_idChanging(int value);
    partial void Onproduct_idChanged();
    partial void Onproduct_category_idChanging(System.Nullable<int> value);
    partial void Onproduct_category_idChanged();
    partial void Onproduct_nameChanging(string value);
    partial void Onproduct_nameChanged();
    partial void Onproduct_descriptionChanging(string value);
    partial void Onproduct_descriptionChanged();
    partial void Onproduct_thumbnail_imageChanging(string value);
    partial void Onproduct_thumbnail_imageChanged();
    partial void Onproduct_priceChanging(System.Nullable<decimal> value);
    partial void Onproduct_priceChanged();
    partial void Onproduct_discountChanging(System.Nullable<decimal> value);
    partial void Onproduct_discountChanged();
    partial void Onproduct_review_positiveChanging(System.Nullable<int> value);
    partial void Onproduct_review_positiveChanged();
    partial void Onproduct_review_negativeChanging(System.Nullable<int> value);
    partial void Onproduct_review_negativeChanged();
    partial void Onproduct_bought_countChanging(System.Nullable<int> value);
    partial void Onproduct_bought_countChanged();
    partial void Onproduct_inventoryChanging(System.Nullable<int> value);
    partial void Onproduct_inventoryChanged();
    #endregion
		
		public product()
		{
			this._user_order_products = new EntitySet<user_order_product>(new Action<user_order_product>(this.attach_user_order_products), new Action<user_order_product>(this.detach_user_order_products));
			this._product_images = new EntitySet<product_image>(new Action<product_image>(this.attach_product_images), new Action<product_image>(this.detach_product_images));
			this._product_category = default(EntityRef<product_category>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					this.Onproduct_idChanging(value);
					this.SendPropertyChanging();
					this._product_id = value;
					this.SendPropertyChanged("product_id");
					this.Onproduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_category_id", DbType="Int")]
		public System.Nullable<int> product_category_id
		{
			get
			{
				return this._product_category_id;
			}
			set
			{
				if ((this._product_category_id != value))
				{
					if (this._product_category.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onproduct_category_idChanging(value);
					this.SendPropertyChanging();
					this._product_category_id = value;
					this.SendPropertyChanged("product_category_id");
					this.Onproduct_category_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_name", DbType="NVarChar(255)")]
		public string product_name
		{
			get
			{
				return this._product_name;
			}
			set
			{
				if ((this._product_name != value))
				{
					this.Onproduct_nameChanging(value);
					this.SendPropertyChanging();
					this._product_name = value;
					this.SendPropertyChanged("product_name");
					this.Onproduct_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_description", DbType="NVarChar(MAX)")]
		public string product_description
		{
			get
			{
				return this._product_description;
			}
			set
			{
				if ((this._product_description != value))
				{
					this.Onproduct_descriptionChanging(value);
					this.SendPropertyChanging();
					this._product_description = value;
					this.SendPropertyChanged("product_description");
					this.Onproduct_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_thumbnail_image", DbType="NVarChar(255)")]
		public string product_thumbnail_image
		{
			get
			{
				return this._product_thumbnail_image;
			}
			set
			{
				if ((this._product_thumbnail_image != value))
				{
					this.Onproduct_thumbnail_imageChanging(value);
					this.SendPropertyChanging();
					this._product_thumbnail_image = value;
					this.SendPropertyChanged("product_thumbnail_image");
					this.Onproduct_thumbnail_imageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_price", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> product_price
		{
			get
			{
				return this._product_price;
			}
			set
			{
				if ((this._product_price != value))
				{
					this.Onproduct_priceChanging(value);
					this.SendPropertyChanging();
					this._product_price = value;
					this.SendPropertyChanged("product_price");
					this.Onproduct_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_discount", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> product_discount
		{
			get
			{
				return this._product_discount;
			}
			set
			{
				if ((this._product_discount != value))
				{
					this.Onproduct_discountChanging(value);
					this.SendPropertyChanging();
					this._product_discount = value;
					this.SendPropertyChanged("product_discount");
					this.Onproduct_discountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_review_positive", DbType="Int")]
		public System.Nullable<int> product_review_positive
		{
			get
			{
				return this._product_review_positive;
			}
			set
			{
				if ((this._product_review_positive != value))
				{
					this.Onproduct_review_positiveChanging(value);
					this.SendPropertyChanging();
					this._product_review_positive = value;
					this.SendPropertyChanged("product_review_positive");
					this.Onproduct_review_positiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_review_negative", DbType="Int")]
		public System.Nullable<int> product_review_negative
		{
			get
			{
				return this._product_review_negative;
			}
			set
			{
				if ((this._product_review_negative != value))
				{
					this.Onproduct_review_negativeChanging(value);
					this.SendPropertyChanging();
					this._product_review_negative = value;
					this.SendPropertyChanged("product_review_negative");
					this.Onproduct_review_negativeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_bought_count", DbType="Int")]
		public System.Nullable<int> product_bought_count
		{
			get
			{
				return this._product_bought_count;
			}
			set
			{
				if ((this._product_bought_count != value))
				{
					this.Onproduct_bought_countChanging(value);
					this.SendPropertyChanging();
					this._product_bought_count = value;
					this.SendPropertyChanged("product_bought_count");
					this.Onproduct_bought_countChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_inventory", DbType="Int")]
		public System.Nullable<int> product_inventory
		{
			get
			{
				return this._product_inventory;
			}
			set
			{
				if ((this._product_inventory != value))
				{
					this.Onproduct_inventoryChanging(value);
					this.SendPropertyChanging();
					this._product_inventory = value;
					this.SendPropertyChanged("product_inventory");
					this.Onproduct_inventoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_user_order_product", Storage="_user_order_products", ThisKey="product_id", OtherKey="product_id")]
		public EntitySet<user_order_product> user_order_products
		{
			get
			{
				return this._user_order_products;
			}
			set
			{
				this._user_order_products.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_product_image", Storage="_product_images", ThisKey="product_id", OtherKey="product_id")]
		public EntitySet<product_image> product_images
		{
			get
			{
				return this._product_images;
			}
			set
			{
				this._product_images.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_category_product", Storage="_product_category", ThisKey="product_category_id", OtherKey="product_category_id", IsForeignKey=true)]
		public product_category product_category
		{
			get
			{
				return this._product_category.Entity;
			}
			set
			{
				product_category previousValue = this._product_category.Entity;
				if (((previousValue != value) 
							|| (this._product_category.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._product_category.Entity = null;
						previousValue.products.Remove(this);
					}
					this._product_category.Entity = value;
					if ((value != null))
					{
						value.products.Add(this);
						this._product_category_id = value.product_category_id;
					}
					else
					{
						this._product_category_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("product_category");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_user_order_products(user_order_product entity)
		{
			this.SendPropertyChanging();
			entity.product = this;
		}
		
		private void detach_user_order_products(user_order_product entity)
		{
			this.SendPropertyChanging();
			entity.product = null;
		}
		
		private void attach_product_images(product_image entity)
		{
			this.SendPropertyChanging();
			entity.product = this;
		}
		
		private void detach_product_images(product_image entity)
		{
			this.SendPropertyChanging();
			entity.product = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.product_category")]
	public partial class product_category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _product_category_id;
		
		private string _product_category_name;
		
		private string _product_category_description;
		
		private EntitySet<discount_event> _discount_events;
		
		private EntitySet<product> _products;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproduct_category_idChanging(int value);
    partial void Onproduct_category_idChanged();
    partial void Onproduct_category_nameChanging(string value);
    partial void Onproduct_category_nameChanged();
    partial void Onproduct_category_descriptionChanging(string value);
    partial void Onproduct_category_descriptionChanged();
    #endregion
		
		public product_category()
		{
			this._discount_events = new EntitySet<discount_event>(new Action<discount_event>(this.attach_discount_events), new Action<discount_event>(this.detach_discount_events));
			this._products = new EntitySet<product>(new Action<product>(this.attach_products), new Action<product>(this.detach_products));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_category_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int product_category_id
		{
			get
			{
				return this._product_category_id;
			}
			set
			{
				if ((this._product_category_id != value))
				{
					this.Onproduct_category_idChanging(value);
					this.SendPropertyChanging();
					this._product_category_id = value;
					this.SendPropertyChanged("product_category_id");
					this.Onproduct_category_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_category_name", DbType="NVarChar(255)")]
		public string product_category_name
		{
			get
			{
				return this._product_category_name;
			}
			set
			{
				if ((this._product_category_name != value))
				{
					this.Onproduct_category_nameChanging(value);
					this.SendPropertyChanging();
					this._product_category_name = value;
					this.SendPropertyChanged("product_category_name");
					this.Onproduct_category_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_category_description", DbType="NVarChar(MAX)")]
		public string product_category_description
		{
			get
			{
				return this._product_category_description;
			}
			set
			{
				if ((this._product_category_description != value))
				{
					this.Onproduct_category_descriptionChanging(value);
					this.SendPropertyChanging();
					this._product_category_description = value;
					this.SendPropertyChanged("product_category_description");
					this.Onproduct_category_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_category_discount_event", Storage="_discount_events", ThisKey="product_category_id", OtherKey="product_category_id")]
		public EntitySet<discount_event> discount_events
		{
			get
			{
				return this._discount_events;
			}
			set
			{
				this._discount_events.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_category_product", Storage="_products", ThisKey="product_category_id", OtherKey="product_category_id")]
		public EntitySet<product> products
		{
			get
			{
				return this._products;
			}
			set
			{
				this._products.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_discount_events(discount_event entity)
		{
			this.SendPropertyChanging();
			entity.product_category = this;
		}
		
		private void detach_discount_events(discount_event entity)
		{
			this.SendPropertyChanging();
			entity.product_category = null;
		}
		
		private void attach_products(product entity)
		{
			this.SendPropertyChanging();
			entity.product_category = this;
		}
		
		private void detach_products(product entity)
		{
			this.SendPropertyChanging();
			entity.product_category = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.product_image")]
	public partial class product_image : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _product_image_id;
		
		private System.Nullable<int> _product_id;
		
		private string _product_image_file_name;
		
		private EntityRef<product> _product;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproduct_image_idChanging(int value);
    partial void Onproduct_image_idChanged();
    partial void Onproduct_idChanging(System.Nullable<int> value);
    partial void Onproduct_idChanged();
    partial void Onproduct_image_file_nameChanging(string value);
    partial void Onproduct_image_file_nameChanged();
    #endregion
		
		public product_image()
		{
			this._product = default(EntityRef<product>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_image_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int product_image_id
		{
			get
			{
				return this._product_image_id;
			}
			set
			{
				if ((this._product_image_id != value))
				{
					this.Onproduct_image_idChanging(value);
					this.SendPropertyChanging();
					this._product_image_id = value;
					this.SendPropertyChanged("product_image_id");
					this.Onproduct_image_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="Int")]
		public System.Nullable<int> product_id
		{
			get
			{
				return this._product_id;
			}
			set
			{
				if ((this._product_id != value))
				{
					if (this._product.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onproduct_idChanging(value);
					this.SendPropertyChanging();
					this._product_id = value;
					this.SendPropertyChanged("product_id");
					this.Onproduct_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_image_file_name", DbType="NVarChar(50)")]
		public string product_image_file_name
		{
			get
			{
				return this._product_image_file_name;
			}
			set
			{
				if ((this._product_image_file_name != value))
				{
					this.Onproduct_image_file_nameChanging(value);
					this.SendPropertyChanging();
					this._product_image_file_name = value;
					this.SendPropertyChanged("product_image_file_name");
					this.Onproduct_image_file_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_product_image", Storage="_product", ThisKey="product_id", OtherKey="product_id", IsForeignKey=true)]
		public product product
		{
			get
			{
				return this._product.Entity;
			}
			set
			{
				product previousValue = this._product.Entity;
				if (((previousValue != value) 
							|| (this._product.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._product.Entity = null;
						previousValue.product_images.Remove(this);
					}
					this._product.Entity = value;
					if ((value != null))
					{
						value.product_images.Add(this);
						this._product_id = value.product_id;
					}
					else
					{
						this._product_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("product");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.user_account")]
	public partial class user_account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_account_id;
		
		private string _user_username;
		
		private string _user_password;
		
		private string _user_gender;
		
		private string _user_email;
		
		private string _user_phonenumber;
		
		private string _user_address;
		
		private string _user_firstname;
		
		private string _user_lastname;
		
		private string _user_member_tier;
		
		private System.Nullable<int> _user_point;
		
		private EntitySet<user_order> _user_orders;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_account_idChanging(int value);
    partial void Onuser_account_idChanged();
    partial void Onuser_usernameChanging(string value);
    partial void Onuser_usernameChanged();
    partial void Onuser_passwordChanging(string value);
    partial void Onuser_passwordChanged();
    partial void Onuser_genderChanging(string value);
    partial void Onuser_genderChanged();
    partial void Onuser_emailChanging(string value);
    partial void Onuser_emailChanged();
    partial void Onuser_phonenumberChanging(string value);
    partial void Onuser_phonenumberChanged();
    partial void Onuser_addressChanging(string value);
    partial void Onuser_addressChanged();
    partial void Onuser_firstnameChanging(string value);
    partial void Onuser_firstnameChanged();
    partial void Onuser_lastnameChanging(string value);
    partial void Onuser_lastnameChanged();
    partial void Onuser_member_tierChanging(string value);
    partial void Onuser_member_tierChanged();
    partial void Onuser_pointChanging(System.Nullable<int> value);
    partial void Onuser_pointChanged();
    #endregion
		
		public user_account()
		{
			this._user_orders = new EntitySet<user_order>(new Action<user_order>(this.attach_user_orders), new Action<user_order>(this.detach_user_orders));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_account_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int user_account_id
		{
			get
			{
				return this._user_account_id;
			}
			set
			{
				if ((this._user_account_id != value))
				{
					this.Onuser_account_idChanging(value);
					this.SendPropertyChanging();
					this._user_account_id = value;
					this.SendPropertyChanged("user_account_id");
					this.Onuser_account_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_username", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string user_username
		{
			get
			{
				return this._user_username;
			}
			set
			{
				if ((this._user_username != value))
				{
					this.Onuser_usernameChanging(value);
					this.SendPropertyChanging();
					this._user_username = value;
					this.SendPropertyChanged("user_username");
					this.Onuser_usernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_password", DbType="VarChar(255) NOT NULL", CanBeNull=false)]
		public string user_password
		{
			get
			{
				return this._user_password;
			}
			set
			{
				if ((this._user_password != value))
				{
					this.Onuser_passwordChanging(value);
					this.SendPropertyChanging();
					this._user_password = value;
					this.SendPropertyChanged("user_password");
					this.Onuser_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_gender", DbType="NVarChar(10)")]
		public string user_gender
		{
			get
			{
				return this._user_gender;
			}
			set
			{
				if ((this._user_gender != value))
				{
					this.Onuser_genderChanging(value);
					this.SendPropertyChanging();
					this._user_gender = value;
					this.SendPropertyChanged("user_gender");
					this.Onuser_genderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_email", DbType="VarChar(255)")]
		public string user_email
		{
			get
			{
				return this._user_email;
			}
			set
			{
				if ((this._user_email != value))
				{
					this.Onuser_emailChanging(value);
					this.SendPropertyChanging();
					this._user_email = value;
					this.SendPropertyChanged("user_email");
					this.Onuser_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_phonenumber", DbType="Char(12)")]
		public string user_phonenumber
		{
			get
			{
				return this._user_phonenumber;
			}
			set
			{
				if ((this._user_phonenumber != value))
				{
					this.Onuser_phonenumberChanging(value);
					this.SendPropertyChanging();
					this._user_phonenumber = value;
					this.SendPropertyChanged("user_phonenumber");
					this.Onuser_phonenumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_address", DbType="NVarChar(MAX)")]
		public string user_address
		{
			get
			{
				return this._user_address;
			}
			set
			{
				if ((this._user_address != value))
				{
					this.Onuser_addressChanging(value);
					this.SendPropertyChanging();
					this._user_address = value;
					this.SendPropertyChanged("user_address");
					this.Onuser_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_firstname", DbType="NVarChar(255)")]
		public string user_firstname
		{
			get
			{
				return this._user_firstname;
			}
			set
			{
				if ((this._user_firstname != value))
				{
					this.Onuser_firstnameChanging(value);
					this.SendPropertyChanging();
					this._user_firstname = value;
					this.SendPropertyChanged("user_firstname");
					this.Onuser_firstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_lastname", DbType="NVarChar(255)")]
		public string user_lastname
		{
			get
			{
				return this._user_lastname;
			}
			set
			{
				if ((this._user_lastname != value))
				{
					this.Onuser_lastnameChanging(value);
					this.SendPropertyChanging();
					this._user_lastname = value;
					this.SendPropertyChanged("user_lastname");
					this.Onuser_lastnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_member_tier", DbType="NVarChar(255)")]
		public string user_member_tier
		{
			get
			{
				return this._user_member_tier;
			}
			set
			{
				if ((this._user_member_tier != value))
				{
					this.Onuser_member_tierChanging(value);
					this.SendPropertyChanging();
					this._user_member_tier = value;
					this.SendPropertyChanged("user_member_tier");
					this.Onuser_member_tierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_point", DbType="Int")]
		public System.Nullable<int> user_point
		{
			get
			{
				return this._user_point;
			}
			set
			{
				if ((this._user_point != value))
				{
					this.Onuser_pointChanging(value);
					this.SendPropertyChanging();
					this._user_point = value;
					this.SendPropertyChanged("user_point");
					this.Onuser_pointChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_account_user_order", Storage="_user_orders", ThisKey="user_account_id", OtherKey="user_account_id")]
		public EntitySet<user_order> user_orders
		{
			get
			{
				return this._user_orders;
			}
			set
			{
				this._user_orders.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_user_orders(user_order entity)
		{
			this.SendPropertyChanging();
			entity.user_account = this;
		}
		
		private void detach_user_orders(user_order entity)
		{
			this.SendPropertyChanging();
			entity.user_account = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.user_order")]
	public partial class user_order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_order_id;
		
		private System.Nullable<int> _user_account_id;
		
		private System.Nullable<System.DateTime> _order_time;
		
		private System.Nullable<bool> _is_processed;
		
		private System.Nullable<bool> _is_submitted;
		
		private EntitySet<user_order_product> _user_order_products;
		
		private EntityRef<user_account> _user_account;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_order_idChanging(int value);
    partial void Onuser_order_idChanged();
    partial void Onuser_account_idChanging(System.Nullable<int> value);
    partial void Onuser_account_idChanged();
    partial void Onorder_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onorder_timeChanged();
    partial void Onis_processedChanging(System.Nullable<bool> value);
    partial void Onis_processedChanged();
    partial void Onis_submittedChanging(System.Nullable<bool> value);
    partial void Onis_submittedChanged();
    #endregion
		
		public user_order()
		{
			this._user_order_products = new EntitySet<user_order_product>(new Action<user_order_product>(this.attach_user_order_products), new Action<user_order_product>(this.detach_user_order_products));
			this._user_account = default(EntityRef<user_account>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_order_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int user_order_id
		{
			get
			{
				return this._user_order_id;
			}
			set
			{
				if ((this._user_order_id != value))
				{
					this.Onuser_order_idChanging(value);
					this.SendPropertyChanging();
					this._user_order_id = value;
					this.SendPropertyChanged("user_order_id");
					this.Onuser_order_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_account_id", DbType="Int")]
		public System.Nullable<int> user_account_id
		{
			get
			{
				return this._user_account_id;
			}
			set
			{
				if ((this._user_account_id != value))
				{
					if (this._user_account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_account_idChanging(value);
					this.SendPropertyChanging();
					this._user_account_id = value;
					this.SendPropertyChanged("user_account_id");
					this.Onuser_account_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> order_time
		{
			get
			{
				return this._order_time;
			}
			set
			{
				if ((this._order_time != value))
				{
					this.Onorder_timeChanging(value);
					this.SendPropertyChanging();
					this._order_time = value;
					this.SendPropertyChanged("order_time");
					this.Onorder_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_processed", DbType="Bit")]
		public System.Nullable<bool> is_processed
		{
			get
			{
				return this._is_processed;
			}
			set
			{
				if ((this._is_processed != value))
				{
					this.Onis_processedChanging(value);
					this.SendPropertyChanging();
					this._is_processed = value;
					this.SendPropertyChanged("is_processed");
					this.Onis_processedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_submitted", DbType="Bit")]
		public System.Nullable<bool> is_submitted
		{
			get
			{
				return this._is_submitted;
			}
			set
			{
				if ((this._is_submitted != value))
				{
					this.Onis_submittedChanging(value);
					this.SendPropertyChanging();
					this._is_submitted = value;
					this.SendPropertyChanged("is_submitted");
					this.Onis_submittedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_order_user_order_product", Storage="_user_order_products", ThisKey="user_order_id", OtherKey="user_order_id")]
		public EntitySet<user_order_product> user_order_products
		{
			get
			{
				return this._user_order_products;
			}
			set
			{
				this._user_order_products.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_account_user_order", Storage="_user_account", ThisKey="user_account_id", OtherKey="user_account_id", IsForeignKey=true)]
		public user_account user_account
		{
			get
			{
				return this._user_account.Entity;
			}
			set
			{
				user_account previousValue = this._user_account.Entity;
				if (((previousValue != value) 
							|| (this._user_account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._user_account.Entity = null;
						previousValue.user_orders.Remove(this);
					}
					this._user_account.Entity = value;
					if ((value != null))
					{
						value.user_orders.Add(this);
						this._user_account_id = value.user_account_id;
					}
					else
					{
						this._user_account_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("user_account");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_user_order_products(user_order_product entity)
		{
			this.SendPropertyChanging();
			entity.user_order = this;
		}
		
		private void detach_user_order_products(user_order_product entity)
		{
			this.SendPropertyChanging();
			entity.user_order = null;
		}
	}
}
#pragma warning restore 1591
